### ISSUE TITLE
Maybe work with me?

### ISSUE THREAD

**Issue by wdunn001** [AckerApple/agm-overlays#9]
I need a more comprehensive version of AGM and I am Working on building a fork. 
I am using the google maps types instead of custom objects and have refactored a whole lot of mess. One of the items I need is custom overlays and I have already started integrating and refactoring something based on your code. I wondered if you would be interested in helping me flesh it out?

https://github.com/wdunn001/angular-google-maps

the custom overlay
https://github.com/wdunn001/angular-google-maps/blob/master/packages/core/directives/agm-overlay.ts

current package @agme/core

**Comment by AckerApple** [comment]
I am glad to hear you have the opinion that you do, of agm-core. We used it because of time constraints and only available Angular package. It taught me new ways to approach Providers and I have respect for the package but yeah it needs to be washed. I myself have had to jump threw hoops to keep my compatibility up because an overlay marker should just be like an extension of marker but the way its written makes it convoluted to just extend marker.

I will be needing map upgrades here soon within weeks, myself. I can take a look at where you are then to make choices about getting onto your version, if I do. I am swamped currently.

Let me know if you need knowledge. I typically always have that.
